# Generated by Django 2.1.5 on 2019-02-03 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.IntegerField(choices=[(1, 'Workflow'), (2, 'Task')])),
                ('object_id', models.IntegerField(default=uuid.uuid4)),
                ('state', models.IntegerField(choices=[(1, 'PENDING'), (2, 'READY'), (3, 'RUNNING'), (4, 'STOPPED'), (5, 'ENDED'), (6, 'EXCEPTION_OCCURED')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaUserAssoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskExec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'PENDING'), (2, 'READY'), (3, 'RUNNING'), (4, 'STOPPED'), (5, 'ENDED'), (6, 'EXCEPTION_OCCURED')], default=1)),
                ('data', django_mysql.models.JSONField(default=dict)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifier.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowExec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'PENDING'), (2, 'READY'), (3, 'RUNNING'), (4, 'STOPPED'), (5, 'ENDED'), (6, 'EXCEPTION_OCCURED')], default=1)),
                ('data', django_mysql.models.JSONField(default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifier.Workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.TaskExec')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='taskexec',
            name='workflow_exec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.WorkflowExec'),
        ),
        migrations.AddField(
            model_name='metauserassoc',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metaflow', to='executor.WorkflowExec'),
        ),
        migrations.AddField(
            model_name='metauserassoc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userflow', to='executor.WorkflowExec'),
        ),
    ]
