# Generated by Django 2.1.5 on 2019-01-20 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executor', '0001_initial'),
        ('specifier', '0002_auto_20190120_2141'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowexec',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifier.Workflow'),
        ),
        migrations.AddField(
            model_name='taskexec',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifier.Task'),
        ),
        migrations.AddField(
            model_name='taskexec',
            name='workflow_exec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.WorkflowExec'),
        ),
    ]
