PENDING = 'PENDING'
READY = 'READY' #ready is assigned
RUNNING = 'RUNNING'
STOPPED = 'STOPPED'
ENDED = 'ENDED'
EXCEPTION_OCCURED = 'EXCEPTION_OCCURED'

states = ((1, PENDING),(2,READY),(3,RUNNING),(4,STOPPED),(5, ENDED), (6,EXCEPTION_OCCURED))