# Generated by Django 2.1.5 on 2019-02-03 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('operand', django_mysql.models.JSONField(default=dict)),
                ('operator', django_mysql.models.JSONField(default=dict)),
                ('constant', django_mysql.models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.IntegerField(choices=[(1, 'PENDING'), (2, 'READY'), (3, 'RUNNING'), (4, 'STOPPED'), (5, 'ENDED'), (6, 'EXCEPTION_OCCURED')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifier.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specifier.Condition')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifier.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('task_type', models.IntegerField(choices=[(1, 'meta'), (2, 'non-meta')], default=1)),
                ('description', models.TextField()),
                ('input_params', django_mysql.models.JSONField(default=dict)),
                ('output_params', django_mysql.models.JSONField(default=dict)),
                ('data', django_mysql.models.JSONField(default=dict)),
                ('form', django_mysql.models.JSONField(default=dict)),
                ('handler', django_mysql.models.JSONField(default=dict)),
                ('rule_expression', django_mysql.models.JSONField(default=dict)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifier.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task_Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifier.Rule')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifier.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('workflow_type', models.IntegerField(choices=[(1, 'meta'), (2, 'non-meta')], default=1)),
                ('description', models.TextField()),
                ('constants', django_mysql.models.JSONField(default=dict)),
                ('roles', django_mysql.models.JSONField(default=dict)),
                ('resources', django_mysql.models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='specifier.Workflow'),
        ),
        migrations.AddField(
            model_name='rule',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifier.Workflow'),
        ),
        migrations.AddField(
            model_name='roleassign',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifier.Workflow'),
        ),
        migrations.AddField(
            model_name='event',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifier.Task'),
        ),
        migrations.AddField(
            model_name='condition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifier.Workflow'),
        ),
    ]
